### ISSUE TITLE
compile problems with LTO enabled

### ISSUE THREAD

**Issue by czanik** [algernon/riemann-c-client#25]
openSUSE just enabled LTO ( https://en.opensuse.org/openSUSE:LTO ) in Factory/Tumbleweed. Compilation fails with the following error:
```
[   77s]   CC       lib/riemann/client/lib_libriemann_client_la-tls.lo
[   77s]   CC       lib/riemann/client/lib_libriemann_client_la-udp.lo
[   77s]   CC       src/src_riemann_client-riemann-client.o
[   77s]   CCLD     lib/libriemann-client.la
[   79s]   CCLD     src/riemann-client
[   80s] /usr/lib64/gcc/aarch64-suse-linux/9/../../../../aarch64-suse-linux/bin/ld: /tmp/riemann-client.uCG7fv.ltrans0.ltrans.o: in function `client_query':
[   80s] <artificial>:(.text+0x39c): undefined reference to `riemann_client_create'
[   80s] /usr/lib64/gcc/aarch64-suse-linux/9/../../../../aarch64-suse-linux/bin/ld: /tmp/riemann-client.uCG7fv.ltrans0.ltrans.o: in function `client_send':
[   80s] <artificial>:(.text+0x10f4): undefined reference to `riemann_client_create'
[   80s] collect2: error: ld returned 1 exit status
[   80s] make[1]: *** [Makefile:761: src/riemann-client] Error 1
[   80s] make: *** [Makefile:546: all] Error 2
[   80s] error: Bad exit status from /var/tmp/rpm-tmp.Go1VCc (%build)
```
When using ```%define _lto_cflags %{nil}``` in the spec file to disable LTO, compilation works as expected.

It's not an urgent issue, as workaround exists, but on a longer term other distros might also be affected.

**Comment by algernon** [comment]
I suspect what the problem here may be. Out of curiosity, if you change [this](https://github.com/algernon/riemann-c-client/blob/ec8dee6e475f502e7a3b41fce21693f1b9385d0f/configure.ac#L113) line to read `AC_DEFINE_UNQUOTED(HAVE_VERSIONING, 0,` (the next line remains unchanged), regenerate the autotools files, and recompile, does the error still happen?

**Comment by czanik** [comment]
Yeah, it seems to have fixed the problem, all builds are green when using the modified source tgz:

https://build.opensuse.org/package/show/home:czanik:syslog-ng-githead/riemann-c-client

**Comment by algernon** [comment]
Thanks, that confirms my suspicion. I'll have a proper fix in place as soon as I can reproduce the problem. Until then, please use the disable LTO fix instead of the hack, symbol versions are important :)

**Comment by algernon** [comment]
Oh, symbol versioning + lto is [not supported](https://en.opensuse.org/openSUSE:LTO#Symbol_versioning) yet. So the "correct" fix at the moment is to disable LTO in the spec file. The attribute-based workaround mentioned there is not something I'm comfortable with, because it also requires a special compiler flag too.

So until GCC supports LTO and symbol versioning together, one of them needs to be disabled. Symbol versioning needs to remain enabled, otherwise Bad Things Happen (like, if you have something compiled against a symbol-versioned riemann-c-client, and upgrade the library to a non-versioned lib, the program will fail to start, because it won't find the symbols).

**Comment by czanik** [comment]
Thanks. I changed back to the original dist tgz and disabled LTO in the spec file.
