### ISSUE TITLE
Support for a TLS library other than GnuTLS

### ISSUE THREAD

**Issue by jirutka** [algernon/riemann-c-client#26]
Could you please consider adding support for [mbed TLS](https://github.com/ARMmbed/mbedtls) (formerly PolarSSL), OpenSSL or some other TLS library that is not as huge as GnuTLS?

**Comment by algernon** [comment]
I will happily add support for any TLS library that is compatible with the LGPL-3.0, without adding a linking exception, if someone contributes said support. I do not have any plans on working towards this myself, I'm afraid.

Looks like mbed TLS fits that bill, so that could be an option. The library already supports two versions of GnuTLS, neatly separated and contained, so adding mbed TLS support shouldn't be _too_ hard, and I'd be thrilled to merge such a PR.

**Comment by algernon** [comment]
I went ahead and had a look at mbed TLS, to figure out how trivial it would be to add. Turns out, it's not _very_ hard, but there are a few differences between how GnuTLS and mbed TLS wrap lower-level socket stuff. Whereas with GnuTLS, I'm expected to handle the network parts myself, mbed TLS wants to wrap it. So I see two options going forward:

1) Refactor riemann-c-client to allow the kind of abstraction mbed TLS wants
2) Continue with the status quo, and set up `mbedtls_net_context` ourselves.

I think the second option would be far easier, but potentially also less reliable. I have no experience with mbed TLS, so this is where I'll stop, and let someone else take it from here. I pushed a build system change to the [mbed-tls](https://github.com/algernon/riemann-c-client/tree/mbed-tls) branch, that sets up the autotools stuff to allow switching between gnutls and mbedtls. All that's left is the actual implementation, and some conditional includes in `lib/riemann/client/tls.c`, something I will not have the time to do anytime soon.

**Comment by algernon** [comment]
With the recent release of OpenSSL 3.0, they changed the license to Apache-2.0, which is LGPL-3+ compatible, unlike the previous license combo. Thus OpenSSL became another possible option to support. I'll have a look at some point, but as always, happy to accept patches.

**Comment by algernon** [comment]
Had a quick look at OpenSSL, and while it _appears_ to support the kind of setup we do now with GnuTLS (doing the connection ourselves, and gnutls bolting onto that), it really looks like we'd be better off by just using the OpenSSL connection methods and whatnot. That'd benefit mbedTLS aswell.

This means that before adding support for OpenSSL or mbedTLS, we first need to refactor how TLS (the connection part, in particular) is implemented in riemann-c-client.

**Comment by algernon** [comment]
I have some good news! I think I found a reasonably straightforward way to refactor the parts of the library that need to be changed to support OpenSSL (& mbed-tls).

The next thing I need to figure out is what an supporting alternative TLS library will mean for ABI compatibility, and also what'll happen when compiled with a different TLS library. As in, if I have a program compiled against libriemann-client+GnuTLS, what happens if I run it with libriemann-client+OpenSSL? Guess I'll have to figure that out once the support for the library lands. Way back when I originally wrote the library, I knew, but that was a good couple of years ago, and I completely forgot.

**Comment by algernon** [comment]
Very rough, half-implementation of OpenSSL support is on the [`tls/openssl`](https://github.com/algernon/riemann-c-client/tree/tls/openssl) branch. It leaks memory, does nearly no error checking, and does not support connection timeouts (so the test suite fails, because it stalls forever), but `src/riemann-client` is able to connect to riemann via tls and even communicate.

I don't know when I'll have time to work on it more, but the basics are there. The biggest blocker is timeout support, we'll need to put the BIO in non-blocking mode, and work with that, at least for the connection part, setting a timeout via the CTX might work for reads and writes after. I _think_. But I have little clue about what I'm doing, it's mostly man page skimming and finding random examples.

The branch requires OpenSSL 3.0, by the way. It might compile against earlier versions too, but I haven't checked, and prior versions are license-incompatible anyway.

**Comment by algernon** [comment]
I was reading my news feed yesterday, and stumbled upon [wolfSSL](https://www.wolfssl.com/), and had a look. It had good docs, and an API that was easy to adapt to. So now we have a [`tls/wolfssl`](https://github.com/algernon/riemann-c-client/tree/tls/wolfssl) branch too.

Unlike the openSSL branch, this not only compiles, but [passes the test suite](https://ci.madhouse-project.org/algernon/riemann-c-client/75/6/7) aswell.

I have to conduct some more tests, and figure out how to handle the ABI difference when compiled with either TLS library, but will merge wolfSSL support after.

**Comment by algernon** [comment]
The branch has now been merged to master. As wolfSSL is even smaller than OpenSSL, I'll consider this issue resolved. I'll keep the `tls/openssl` branch around, if someone wants to take it further and finish it, or if I'll get there myself (though, with wolfSSL support merged, I don't think I'll get there anytime soon).
