### ISSUE TITLE
TCP socket timeout seems to break the client

### ISSUE THREAD

**Issue by matoikar** [algernon/riemann-c-client#9]
syslog ng module is using this client and it seems to fail to handle TCP FIN from remote connection on timeout. 

If no messages are sent for X seconds, my remote riemann server / ELB in AWS sends back TCP FIN (60 seconds). The riemann client responds with ACK. When after 80s I write a log entry to syslog and it attempts to send the message using the riemann client the sending fails as TCP connection has been closed. I can see in tcpdump that the message is reattempted multiple times. 

The client never recovers from the lost connection.

**Comment by algernon** [comment]
This behaviour is kind of intentional, because riemann_c_client operates in a blocking mode. I could poll the fd to see if it is still there before doing a read or a write, but that won't help when the connection goes away in the middle of an operation.

The solution to this is adding a timeout, and that is left for the application that uses the library (because there are many ways to do it, and different applications may opt for different methods).

In case of syslog-ng, I have a [PoC patch](https://github.com/algernon/syslog-ng/commit/986404a56e01485be215490142090a3d3e1f4614) that adds a 5 second timeout on platforms that support it.

Mind you, having introduced the `riemann_client_option_t` stuff, I can add this timeout stuff to the library itself. But syslog-ng will still have to be updated to use the new option, and the option will only work on platforms that support `SO_RCVTIMEO` and `SO_SNDTIMEO`.

**Comment by algernon** [comment]
On the other hand, I can't introduce options for TCP without breaking the API and the ABI. A separate function it will be then.
